// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXB6FZPCJRzJ-xcSJtQTrMzAu30UI2Db4',
    appId: '1:307842650757:web:0b6314f953decdff040fec',
    messagingSenderId: '307842650757',
    projectId: 'expense-tracker-6af1b',
    authDomain: 'expense-tracker-6af1b.firebaseapp.com',
    storageBucket: 'expense-tracker-6af1b.firebasestorage.app',
    measurementId: 'G-FN3YZKJ4B2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4KcO_okYI8hZjU7nMBl0Sd1FCNTsvVgU',
    appId: '1:307842650757:android:b1634fd701ded5e9040fec',
    messagingSenderId: '307842650757',
    projectId: 'expense-tracker-6af1b',
    storageBucket: 'expense-tracker-6af1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_hgeE3oeVgxZ_2Ey0n2-2i778HjFLXb8',
    appId: '1:307842650757:ios:c60751b284df24bc040fec',
    messagingSenderId: '307842650757',
    projectId: 'expense-tracker-6af1b',
    storageBucket: 'expense-tracker-6af1b.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_hgeE3oeVgxZ_2Ey0n2-2i778HjFLXb8',
    appId: '1:307842650757:ios:c60751b284df24bc040fec',
    messagingSenderId: '307842650757',
    projectId: 'expense-tracker-6af1b',
    storageBucket: 'expense-tracker-6af1b.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXB6FZPCJRzJ-xcSJtQTrMzAu30UI2Db4',
    appId: '1:307842650757:web:5ee18e2ce5615514040fec',
    messagingSenderId: '307842650757',
    projectId: 'expense-tracker-6af1b',
    authDomain: 'expense-tracker-6af1b.firebaseapp.com',
    storageBucket: 'expense-tracker-6af1b.firebasestorage.app',
    measurementId: 'G-VD572T88Y9',
  );
}
