include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    file_names: ignore
    deprecated_member_use: ignore
    non_constant_identifier_names: ignore
    curly_braces_in_flow_control_structures: ignore
    unrelated_type_equality_checks: ignore
    use_build_context_synchronously: ignore
    unused_local_variable: ignore
    must_be_immutable: ignore
    avoid_types_as_parameter_names: ignore
